### PR TITLE
Micha mans networks and new folder structure

### PR DESCRIPTION
**Pull request by MichaMans**
This changes the repo structure to buildings, networks and the comparison tool.

@HichamJohra I changed the github url to this branch for testing purpose. I also refactored the python code to throw less pep8 errors. What do you think?

### CODE REVIEW

**Comment by HichamJohra** [comment]
@MichaMans thanks for the thorough review of my code.
From what I can see it is mostly '' changed into "", some empty indentations removed, some simplification steps like Return round(result, 2) and breaking down some lines of codes into several lines.
For the last thing, I don't get always why breaking down short lines into several lines, like for example: 

    frame1 = tk.LabelFrame(
        gui, text="Case Type for DESTEST Comparison", width=400, height=60
    )

or

    frame1.pack_propagate(
        0
    )  # Disable resizing of the frame when widgets are packed or resized inside

is there a rule of thumb about when breaking it down into several lines or not?

**Comment by MichaMans** [comment]
@HichamJohra I used black https://github.com/psf/black which give a good starting point of a well formated file. Regarding the line length it was 80 characters for a long time. At the moment the is not that clear rule anymore I think, me in personal, I still like the 80 characters as this is the best line length to have to files side by side. Regarding the things black formatted, it was mainly the whitespaces I guess. So no whitespaces at end of line or (2 * 2) always needs whitespaces between the operator and the number as well as always whitespaces after commas or no whitespace between function call and the breackets etc. I guess this is fine then.

Do you think we should merge this? Did it work for you? If so, I change the url back to master and we can merge

**Comment by HichamJohra** [comment]
@MichaMans ok, I did not know about Black, but that's good to know.
I might rebut some of the formatings in the next version of my code, but I will try to stick to the Black formating as much as possible.
I think you can merge now.
Thanks

**Comment by MichaMans** [comment]
@HichamJohra perfect, thanks. I changed back to master branch url and merge it

**Pull request merged**
