### PR TITLE
Test GitHub actions

### LINKED ISSUE #5: Use github actions to auto-compile a windows binary for the comparison tool
With github actions it should be possible to auto-compile a standalone windows binary for the comparison tool. I'll have a deeper look into it.

### PR DESCRIPTION
**Pull request by MichaMans**
this closes #5 

It introduced github actions to the repository and automatically builds the comparison tool as standalone binary exe for windows. Users can now download from the latest successful job from the https://github.com/ibpsa/project1-destest/actions the compiled artifacts and use the comparison tool without having python installed.

@HichamJohra could you please test if thats working 😃

### CODE REVIEW

**Comment by HichamJohra** [comment]
@MichaMans , not sure about what to do on https://github.com/ibpsa/project1-destest/actions
I've tried several things, but nothing that resulted in giving me an installer setup file or an .exe file.
I need more instructions :)

**Comment by MichaMans** [comment]
@HichamJohra ok I see. Somehow the actions stopped. But if the actual action builds 
image
e.g. this will then be green. You can have a look at the latest action. e.g. this one: https://github.com/ibpsa/project1-destest/actions/runs/440633693
an if it succeeds, you should be able to find an artifact there at the page. This artifact can be downloaded and used as it is a compiled binary exe.
image

**Comment by HichamJohra** [comment]
@MichaMans I managed to build the .exe and run it. It works fine until the plot generation (last step) that fails.

**Comment by MichaMans** [comment]
@HichamJohra Sorry that I am not so clear here 🙈 

The only thing you need to test is the actual automatic build. so the binary which ist compiled by the github actions. I set this action up to compile a new exe on every new push to the master branch. This autocompiled exe can be downloaded from the actions page. eg this one here: [file](https://github.com/ibpsa/project1-destest/suites/1717648093/artifacts/32471462) or [link to the page](https://github.com/ibpsa/project1-destest/actions/runs/440633693). Please download it and test this one. There is no need to build it locally on your own machine. at least thats the intention for the implementation 😃 

And yes, the local build is a bit tricky when it comes to the plots, but I found a workaround (https://stackoverflow.com/a/50078780)

**Comment by HichamJohra** [comment]
@MichaMans that's super nice to have such feature.
unfortunately, the .exe you've built does not work on my computer.
it stays with the window without anything happening (contrary to the .exe I have built locally)

image

**Comment by MichaMans** [comment]
@HichamJohra ahh thats a pitty. For me the startup takes some time. so if you waited for around 30-90s we can agree on thats not working. But at my machine its working fine besides the long startup. (I can have a look at optimizing that later on)

**Comment by HichamJohra** [comment]
@MichaMans absolutelly nothing even after 5 min, whereas my locally complied application was starting up right away

**Comment by MichaMans** [comment]
@HichamJohra damn. Just tried it with my private machine. Works fine and startup take about 5-10 s with the window active. But thats a faster machine. Mhhh but anyways, if its not working for you we might bring in a broader test group. Maybe I'll write a mail to the subgroup after the holidays and someone can test it in addition. So for me I am out until next week. Wish you good holidays! 🎄

**Comment by HichamJohra** [comment]
@MichaMans perfect, let's do that
Have a merry Christmas !

**Comment by MichaMans** [comment]
@HichamJohra this seems to work for some people. SHould we merge until we see a better working option?

**Comment by HichamJohra** [comment]
yes

**Pull request merged**
