### PR TITLE
Update DESTEST_comparison_tool.py

### PR DESCRIPTION
**Pull request by HichamJohra**
- Fixed minor mistakes.
- Added "Echo ON" and "Echo OFF" mode to the interface so that the user can display or not echo from scripts and figures pop up window in IDE.
- Added selection of folder to save result data: figures and result table. The user thus does not need a Python IDE to visualize the results of the comparison tool.
- Fixed and compacted some echo "print" into  1 line.

### CODE REVIEW

**Comment by MichaMans** [comment]
@HichamJohra Thanks for these improvements. I really like the "save to folder" option 😄 Unfortunately there is one thing which is not working correctly. Can you confirm and reproduce the error:
- if I save the plots to the folders, the Trnsys Label for the Temperature Plots is cut by the first character

At the moment I don't see the error in the code and I already try a few minutes to find it. Maybe you can have a look at that again? Would be great! Besides that, everything seems to work good 👍 

image

**Comment by HichamJohra** [comment]
@MichaMans . Good catch ! I found the mistake. I used .lstrip() to remove the prefix of the column name of the dataframe instead of .replace(). lstrip() does not remove a string but all occurrences of char in the string input.
I have edited the code and pushed it to the same patch, but I cannot see the change in the preview...
lines and 4087, 4169, 4246 should now be with list_destest_cases = list(df_destest_cases.columns.str.replace(prefix, ""))
I've tested it and it works fine now.
I have not seen the issue because of extreme luck in the naming of the cases and the parameters :)

**Comment by MichaMans** [comment]
@HichamJohra Is it your intention to keep the prefixes now? Because now the plot looks like: 

This is fine for me if it is your intention as well.

image

**Comment by HichamJohra** [comment]
@MichaMans you are correct, this is a mistake. My fix did not work because .replace() cannot be applied to a list, so I made a work around by using a for loop through all elements of the target list.

Hope it works now

**Review by MichaMans — APPROVED** [review]
@HichamJohra now it looks like expected. Thanks alot!

**Pull request merged**
